### ISSUE TITLE
[JavaScript] Ladereihenfolge

### ISSUE THREAD

**Issue by cereal** [collective/plonetheme.tokyo#71]
Hallo zusammen,

Herr Zingsheim hat uns ein Problem gemeldet, wenn er versucht in Standard Plone Ordnern Objekte per Drag&Drop zu verschieben. Wir haben das Problem soweit runterbrechen können, dass manchmal das JavaScript, welches für das Drag&Drop zuständig ist erst spät geladen wird. Dann funktioniert es nicht mehr und führt zu folgender Exception:

```
Uncaught TypeError: r is not a function
    at HTMLTableRowElement.<anonymous> (logged-in.js:1:357635)
    at HTMLTableRowElement.dispatch (default.js:3:12444)
    at p.dispatch (logged-in.js:3:132541)
    at HTMLTableRowElement.<anonymous> (logged-in.js:3:131087)
    at Function.each (default.js:2:2881)
    at n.fn.init.each (default.js:2:846)
    at Object.hijack (logged-in.js:3:130989)
    at HTMLDocument.handler (logged-in.js:3:130087)
    at HTMLDocument.dispatch (default.js:3:12444)
    at p.dispatch (logged-in.js:3:132541)
```

Ist das bereits in einer aktuellen plonetheme.tokyo Version gefixt? Falls nicht bitte sicherstellen, dass zuerst alle JS geladen werden und dann erst in die Ausführung kommen. 

Vielen Dank und beste Grüße,
Kai

**Comment by santonelli** [comment]
Soviel ich weiß wird das in p.tokyo in den Scripts berücksichtigt. Für den konkreten Fall (ggf. Anpassung im Projekt vorhanden) bitte nochmal mit Lars Walther Rücksprachen halten.
